$("#survButton").click(function()
{
	window.location.href="./survPage.html";
});
$("#respButton").click(function()
{
	window.location.href="./respPage.html";
});
$("#voluntButton").click(function()
{
	window.location.href="./voluntPage.html";
});
$("#coordButton").click(function()
{
	window.location.href="./coordPage.html";
});
